name: CI — Run tests

on:
  push:
    branches: 
        - main
        - p_task6_heapsort
    paths:
      - "src/python_tasks/task6/test_heapsort.py"
      - "src/python_tasks/task6/sortings.py"
  pull_request:
    branches:
        - main
        - p_task6_heapsort
    paths:
      - "src/python_tasks/task6/test_heapsort.py"
      - "src/python_tasks/task6/sortings.py"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/python_tasks/task6/requirements.txt

      - name: Run tests for single file
        run: |
          pytest -q src/python_tasks/task6/test_heapsort.py --maxfail=1 --disable-warnings
